version: '3.4'

services:
  entityframeworkcore:
    image: ${DOCKER_REGISTRY-}entityframeworkcore
    build:
      context: .
      dockerfile: EntityFrameworkCore/Dockerfile
  data:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    environment:
      - SA_PASSWORD=zaq12wsx!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
